[package]
name = "epanet-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
faer = { version = "0.23.2", features = ["linalg"] }
hashbrown = "0.16"
rayon = "1.11.0"


[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
