[package]
name = "epanet-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
faer = { version = "0.23.2", features = ["linalg"] }
rand = "0.9.2"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
